package com.ai.accessibility.security;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

/**
 * JWT Utility - Matches Node.js JWT behavior exactly
 */
@Component
public class JwtUtil {
    
    private static final Logger logger = LoggerFactory.getLogger(JwtUtil.class);
    
    @Value("${app.jwt.secret}")
    private String jwtSecret;
    
    private SecretKey getSigningKey() {
        if (jwtSecret == null || jwtSecret.trim().isEmpty()) {
            logger.error("JWT secret is not configured!");
            throw new IllegalStateException("JWT secret is not configured");
        }
        logger.debug("JWT secret loaded (length: {} chars)", jwtSecret.length());
        /**
         * IMPORTANT (compatibility with Node.js jsonwebtoken):
         * Node's jsonwebtoken allows short HMAC secrets. JJWT's Keys.hmacShaKeyFor enforces
         * RFC7518 minimum key sizes and will throw if secret < 256 bits.
         *
         * To keep 100% compatibility with existing tokens generated by the Node backend,
         * we use SecretKeySpec directly and let the HMAC implementation handle key sizing.
         */
        byte[] secretBytes = jwtSecret.getBytes(StandardCharsets.UTF_8);
        return new SecretKeySpec(secretBytes, "HmacSHA256");
    }
    
    /**
     * Generate JWT token - Matches Node.js format exactly
     * Payload: { id: userId }
     */
    public String generateToken(String userId) {
        Map<String, Object> claims = new HashMap<>();
        claims.put("id", userId);
        
        return Jwts.builder()
                .setClaims(claims)
                .setIssuedAt(new Date(System.currentTimeMillis()))
                .setExpiration(new Date(System.currentTimeMillis() + 7 * 24 * 60 * 60 * 1000)) // 7 days
                .signWith(getSigningKey(), SignatureAlgorithm.HS256)
                .compact();
    }
    
    /**
     * Extract user ID from token - Matches Node.js auth middleware
     */
    public String extractUserId(String token) {
        return extractClaim(token, claims -> {
            // Handle both formats: { id } and { user: { id } }
            if (claims.containsKey("id")) {
                return claims.get("id").toString();
            }
            if (claims.containsKey("user")) {
                Map<?, ?> user = (Map<?, ?>) claims.get("user");
                if (user.containsKey("id")) {
                    return user.get("id").toString();
                }
            }
            return null;
        });
    }
    
    public <T> T extractClaim(String token, Function<Claims, T> claimsResolver) {
        final Claims claims = extractAllClaims(token);
        return claimsResolver.apply(claims);
    }
    
    private Claims extractAllClaims(String token) {
        return Jwts.parserBuilder()
                .setSigningKey(getSigningKey())
                .build()
                .parseClaimsJws(token)
                .getBody();
    }
    
    public Boolean isTokenExpired(String token) {
        try {
            Date expiration = extractExpiration(token);
            return expiration.before(new Date());
        } catch (Exception e) {
            logger.warn("Failed to check token expiration: {}", e.getMessage());
            return true; // If we can't parse, consider it expired/invalid
        }
    }
    
    public Date extractExpiration(String token) {
        return extractClaim(token, Claims::getExpiration);
    }
    
    public Boolean validateToken(String token, String userId) {
        final String extractedUserId = extractUserId(token);
        return (extractedUserId != null && extractedUserId.equals(userId) && !isTokenExpired(token));
    }
}
